spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

server:
  port: 8080

application:
  locale: ru_RU

questionnaire:
  csv-file-name: "questions.csv"
  min-right-answers: 1